/**
 * What the CMS is allowed to write, and to which branches.
 *
 * This is the permission model, not a convenience check: the serverless proxy
 * calls it on every write, so "don't touch anything outside content" (the
 * editor guide's §1.7 and §9.5) needs no discipline from the owner and cannot
 * be bypassed by a crafted request. Keep it dependency-free - it runs in the
 * browser and in the function, and both must agree.
 */

/**
 * Only these prefixes, and within each only these extensions. The prefix alone
 * is not enough: `src/content/config.ts` is the authoritative schema and sits
 * directly under one of them, and an uploader that accepts `.svg` or `.html`
 * would be writing script into a path the site serves.
 */
const WRITABLE: ReadonlyArray<{ prefix: string; extensions: readonly string[] }> = [
  { prefix: 'src/content/', extensions: ['.toml', '.mdx'] },
  { prefix: 'public/img/', extensions: ['.jpg', '.jpeg', '.png', '.webp'] },
];

/**
 * Generated derivatives belong to .github/workflows/images.yml. The CMS
 * commits originals only; writing here would fight the bot and break the
 * digest contract that makes these URLs immutably cacheable (AGENTS.md §6.1).
 */
const FORBIDDEN_PREFIXES = ['public/img/_opt/'] as const;

export const DRAFT_BRANCH = 'content-draft';
export const TARGET_BRANCH = 'master';
/**
 * The only branch the site builds besides master. Saves land on the draft,
 * which Vercel does not build; this is pointed at the draft's commit when the
 * preview is opened, so one build serves every save before it.
 */
export const PREVIEW_BRANCH = 'content-preview';
const WRITABLE_BRANCHES = [DRAFT_BRANCH, TARGET_BRANCH] as const;

/**
 * Refs the engine may point at a commit. Wider than the writable set on
 * purpose: `content-preview` never carries content of its own - it is only
 * ever moved onto a commit the draft already holds - so it is a ref this code
 * moves and never a branch content can be written to. Keeping the two lists
 * distinct is what lets the allowlist still describe every ref the engine
 * touches, which is the invariant B-7 pins down.
 */
const MOVABLE_BRANCHES = [...WRITABLE_BRANCHES, PREVIEW_BRANCH] as const;

export type WritableBranch = (typeof WRITABLE_BRANCHES)[number];

export class PathRejected extends Error {
  constructor(
    readonly path: string,
    reason: string,
    /** What was refused, so a rejected read does not report itself as a write. */
    action: 'write' | 'read' | 'move' = 'write',
  ) {
    super(`refusing to ${action} ${JSON.stringify(path)}: ${reason}`);
    this.name = 'PathRejected';
  }
}

/** What is wrong with the shape of `path` itself, whatever it names. */
function shapeRejection(path: string): string | null {
  if (typeof path !== 'string' || path.length === 0) return 'empty path';
  if (path.length > 1024) return 'path too long';
  if (path !== path.normalize('NFC')) return 'path is not NFC-normalised';
  // eslint-disable-next-line no-control-regex
  if (/[\x00-\x1f\x7f]/.test(path)) return 'control character in path';
  if (path.includes('\\')) return 'backslash in path';
  if (path.startsWith('/')) return 'absolute path';
  if (path.includes('//')) return 'empty path segment';
  if (path.includes('%')) return 'percent-encoding in path';

  const segments = path.split('/');
  if (segments.some((s) => s === '.' || s === '..')) return 'relative segment in path';
  if (segments.some((s) => s.length === 0)) return 'empty path segment';
  if (segments.some((s) => s !== s.trim())) return 'padded path segment';
  // Nothing the owner can name begins with a dot, and a `.git` directory
  // reaching GitHub at all - to be refused there rather than here - is the
  // kind of thing this function exists to stop.
  if (segments.some((s) => s.startsWith('.'))) return 'dot-prefixed path segment';
  return null;
}

const extensionOf = (path: string): string => {
  const name = path.split('/').pop() ?? '';
  const dot = name.lastIndexOf('.');
  return dot > 0 ? name.slice(dot).toLowerCase() : '';
};

/** Why `path` may not be written, or null if it may. */
export function pathRejection(path: string): string | null {
  const shape = shapeRejection(path);
  if (shape) return shape;

  if (FORBIDDEN_PREFIXES.some((p) => path.startsWith(p))) {
    return 'generated by the images workflow';
  }

  const area = WRITABLE.find((w) => path.startsWith(w.prefix));
  if (!area) return `outside ${WRITABLE.map((w) => w.prefix).join(' and ')}`;

  const ext = extensionOf(path);
  if (!area.extensions.includes(ext)) {
    return `${ext || 'no extension'} is not one of ${area.extensions.join(', ')} under ${area.prefix}`;
  }
  return null;
}

export const isWritablePath = (path: string): boolean => pathRejection(path) === null;

/**
 * Reading is wider than writing, by exactly one directory.
 *
 * `public/img/_opt/` belongs to the images workflow and the CMS must never
 * write there - that is what keeps the digest contract making those URLs
 * immutably cacheable (AGENTS.md §6.1). Reading them is a different act, and
 * it is how the editor shows a 400px thumbnail instead of pulling a
 * three-megapixel original onto a phone.
 */
const READABLE_EXTRA: ReadonlyArray<{ prefix: string; extensions: readonly string[] }> = [
  { prefix: 'public/img/_opt/', extensions: ['.json', '.avif', '.webp'] },
];

export function readRejection(path: string): string | null {
  const shape = shapeRejection(path);
  if (shape) return shape;

  const area = READABLE_EXTRA.find((r) => path.startsWith(r.prefix));
  if (!area) return pathRejection(path);

  const ext = extensionOf(path);
  return area.extensions.includes(ext)
    ? null
    : `${ext || 'no extension'} is not readable under ${area.prefix}`;
}

export const isReadablePath = (path: string): boolean => readRejection(path) === null;

export function assertReadablePath(path: string): void {
  const reason = readRejection(path);
  if (reason) throw new PathRejected(path, reason, 'read');
}

export function assertWritablePath(path: string): void {
  const reason = pathRejection(path);
  if (reason) throw new PathRejected(path, reason);
}

export function assertWritablePaths(paths: readonly string[]): void {
  for (const p of paths) assertWritablePath(p);
}

export const isWritableBranch = (branch: string): branch is WritableBranch =>
  (WRITABLE_BRANCHES as readonly string[]).includes(branch);

export function assertWritableBranch(branch: string): void {
  if (!isWritableBranch(branch)) {
    throw new PathRejected(branch, `not one of ${WRITABLE_BRANCHES.join(', ')}`);
  }
}

export const isMovableBranch = (branch: string): boolean =>
  (MOVABLE_BRANCHES as readonly string[]).includes(branch);

export function assertMovableBranch(branch: string): void {
  if (!isMovableBranch(branch)) {
    throw new PathRejected(branch, `not one of ${MOVABLE_BRANCHES.join(', ')}`, 'move');
  }
}

/** Images the owner uploads, split by what they are. */
export const IMAGE_DIRS = {
  content: 'public/img/content/',
  recommendations: 'public/img/recommendations/',
} as const;
